libraries:

  Movies:
    reset_overlays: tmdb
    collection_files:
    - file: config/Movies/Movies_suggested.yml
    - file: config/Movies/Movies.yml
    - file: config/Movies/Seasonal.yml
    - file: config/Movies/Networks.yml
    overlay_files:
    - default: mediastinger
      template_variables:
        url: https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/bottom-left/mediastinger-bottom-left-notext.png
        vertical_align: bottom
        vertical_offset: 0
        horizontal_align: right
        horizontal_offset: 0
        back_width: 1000
        back_height: 1500
        back_color: 00

  4K Movies:
    reset_overlays: tmdb
    collection_files:
    - file: config/Movies/Movies_suggested.yml
    - file: config/Movies/Movies.yml
    - file: config/Movies/Seasonal.yml
    - file: config/Movies/Networks.yml
    overlay_files:
    - default: resolution
    - default: mediastinger
      template_variables:
        url: https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/bottom-left/mediastinger-bottom-left-notext.png
        vertical_align: bottom
        vertical_offset: 0
        horizontal_align: right
        horizontal_offset: 0
        back_width: 1000
        back_height: 1500
        back_color: 00

  TV:
    reset_overlays: tmdb
    reapply_overlays: true
    collection_files:
    - file: config/TV/TV_suggested.yml
    - file: config/TV/Networks.yml
    overlay_files:
    - url: https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/Status.yml
    - default: network
      template_variables:
        horizontal_align: left
        horizontal_offset: 0
        vertical_offset: 0
        vertical_align: top
        back_width: 1000
        back_height: 1500
        url: https://raw.githubusercontent.com/TheChrisK/PMM/main/overlays/network-top-left/<<key>>.png
        back_color: 00


settings:
  cache: true
  cache_expiration: 60
  asset_directory:
  - config/assets/movie
  - config/assets/tv
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: false
  create_asset_folders: false
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  minimum_items: 1
  asset_depth: 0
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  default_collection_order:
  delete_not_scheduled: false
  only_filter_missing: false
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  verify_ssl: true
  playlist_sync_to_users: all
  show_missing_episode_assets: false
  show_asset_not_needed: true
  item_refresh_delay: 0
  custom_repo:
  prioritize_assets: false
  playlist_report: true
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:
  run_order:
  - overlays
  - operations
  - metadata
  - collections
  asset_folders: true